// MCP servers installable on this VPS, made available to Claude Desktop locally
// (by syncing the generated claude_desktop_config.json down to the user's machine).

module.exports = [
  {
    id: 'github',
    name: 'GitHub MCP',
    description: 'Repos GitHub : issues, PRs, fichiers, recherche, commits.',
    installType: 'npx',
    npmPackage: '@modelcontextprotocol/server-github',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    envKeys: [{ key: 'GITHUB_PERSONAL_ACCESS_TOKEN', required: true, secret: true,
                 help: 'github.com/settings/tokens — scope: repo, read:org' }],
  },
  {
    id: 'supabase',
    name: 'Supabase MCP',
    description: 'Gestion projets Supabase : tables, SQL, Edge functions.',
    installType: 'npx',
    npmPackage: '@supabase/mcp-server-supabase',
    command: 'npx',
    args: ['-y', '@supabase/mcp-server-supabase'],
    envKeys: [{ key: 'SUPABASE_ACCESS_TOKEN', required: true, secret: true,
                 help: 'supabase.com/dashboard/account/tokens' }],
  },
  {
    id: 'hostinger',
    name: 'Hostinger MCP',
    description: 'API Hostinger : VPS, domaines, DNS, fichiers FTP.',
    installType: 'npx',
    npmPackage: 'hostinger-api-mcp',
    command: 'npx',
    args: ['-y', 'hostinger-api-mcp'],
    envKeys: [{ key: 'HOSTINGER_API_TOKEN', required: true, secret: true,
                 help: 'hpanel.hostinger.com/profile/api' }],
  },
  {
    id: 'premiere-pro',
    name: 'Premiere Pro MCP',
    description: 'Edition Adobe Premiere Pro depuis Claude (le panel CEP doit être installé manuellement sur le poste qui a Premiere).',
    installType: 'git-build',
    repo: 'https://github.com/leancoderkavy/premiere-pro-mcp.git',
    folder: 'premiere-pro-mcp',
    buildCmds: [['npm', ['install']], ['npm', ['run', 'build']]],
    command: 'node',
    args: ['{HOME}/.jarvis-mcps/premiere-pro-mcp/dist/index.js'],
    envKeys: [],
  },
  {
    id: 'after-effects',
    name: 'After Effects MCP',
    description: 'Contrôle Adobe After Effects via ExtendScript (bridge à installer manuellement dans AE).',
    installType: 'git-build',
    repo: 'https://github.com/Dakkshin/after-effects-mcp.git',
    folder: 'after-effects-mcp',
    buildCmds: [['npm', ['install']], ['npm', ['run', 'build']]],
    command: 'node',
    args: ['{HOME}/.jarvis-mcps/after-effects-mcp/build/index.js'],
    envKeys: [],
  },
];
