// Docker services managed by Jarvis OS sidecar.

module.exports = [
  {
    id: 'agent-zero',
    name: 'Agent Zero',
    description: 'Framework agent autonome multi-step (port 8080 → 80).',
    image: 'agent0ai/agent-zero',
    containerName: 'jarvis-agent-zero',
    dockerArgs: ['-p', '8080:80', '-v', 'a0_usr:/a0/usr'],
    cmdArgs: [],
    healthUrl: 'http://localhost:8080',
    exposesAgent: true,
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    description: 'Base vectorielle mémoire long-terme (port 6333).',
    image: 'qdrant/qdrant',
    containerName: 'jarvis-qdrant',
    dockerArgs: ['-p', '6333:6333', '-p', '6334:6334', '-v', 'qdrant_storage:/qdrant/storage'],
    cmdArgs: [],
    healthUrl: 'http://localhost:6333/healthz',
    exposesAgent: false,
  },
  {
    id: 'compreface-postgres',
    name: 'CompreFace (Postgres)',
    description: 'Postgres pour CompreFace.',
    image: 'exadel/compreface-postgres-db:1.2.0',
    containerName: 'jarvis-compreface-db',
    dockerArgs: [
      '-e', 'POSTGRES_USER=compreface',
      '-e', 'POSTGRES_PASSWORD=compreface',
      '-e', 'POSTGRES_DB=frs',
      '-v', 'compreface_db:/var/lib/postgresql/data',
    ],
    cmdArgs: [],
    healthUrl: null,
    exposesAgent: false,
  },
  {
    id: 'compreface',
    name: 'CompreFace',
    description: 'Reconnaissance faciale (UI port 8000).',
    image: 'exadel/compreface-api:1.2.0',
    containerName: 'jarvis-compreface',
    dockerArgs: [
      '-p', '8000:8080',
      '--link', 'jarvis-compreface-db:postgres-db',
      '-e', 'POSTGRES_URL=jdbc:postgresql://postgres-db:5432/frs',
      '-e', 'POSTGRES_USER=compreface',
      '-e', 'POSTGRES_PASSWORD=compreface',
    ],
    cmdArgs: [],
    healthUrl: 'http://localhost:8000',
    exposesAgent: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'LLM local (port 11434). Note: VPS sans GPU → modèles petits seulement.',
    image: 'ollama/ollama',
    containerName: 'jarvis-ollama',
    dockerArgs: ['-p', '11434:11434', '-v', 'ollama_data:/root/.ollama'],
    cmdArgs: [],
    healthUrl: 'http://localhost:11434',
    exposesAgent: false,
  },
];
